# Generated by Django 6.1 on 2026-08-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="หัวข้อแบนเนอร์")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="ข้อความย่อย"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="banners/", verbose_name="รูปภาพแบนเนอร์"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ข้อความบนปุ่ม"
                    ),
                ),
                (
                    "button_url",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="ลิงก์ปุ่ม"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ลำดับการแสดงผล")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
            ],
            options={
                "verbose_name": "สไลด์หน้าแรก (Banner)",
                "verbose_name_plural": "สไลด์หน้าแรก (Banners)",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ชื่อหลักสูตร")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("ปริญญาตรี", "ปริญญาตรี"),
                            ("ปริญญาโท", "ปริญญาโท"),
                            ("ปริญญาเอก", "ปริญญาเอก"),
                            ("หลักสูตรระยะสั้น", "หลักสูตรระยะสั้น"),
                        ],
                        default="ปริญญาตรี",
                        max_length=100,
                        verbose_name="ระดับการศึกษา",
                    ),
                ),
                (
                    "degree_title",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="ชื่อปริญญา (ย่อ/เต็ม)",
                    ),
                ),
                ("description", models.TextField(verbose_name="รายละเอียดหลักสูตร")),
                (
                    "career_opportunities",
                    models.TextField(verbose_name="โอกาสในการประกอบอาชีพ"),
                ),
                (
                    "duration",
                    models.CharField(
                        default="4 ปี", max_length=100, verbose_name="ระยะเวลาศึกษา"
                    ),
                ),
                (
                    "credits",
                    models.CharField(
                        default="120+ หน่วยกิต",
                        max_length=100,
                        verbose_name="จำนวนหน่วยกิต",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fa-laptop-code",
                        max_length=50,
                        verbose_name="ไอคอน FontAwesome (เช่น fa-laptop-code)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="courses/",
                        verbose_name="รูปภาพหลักสูตร",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ลำดับการแสดงผล")),
            ],
            options={
                "verbose_name": "หลักสูตรการศึกษา",
                "verbose_name_plural": "หลักสูตรการศึกษา",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ชื่อ-นามสกุล")),
                (
                    "academic_rank",
                    models.CharField(
                        max_length=100,
                        verbose_name="ตำแหน่งทางวิชาการ (เช่น ผศ.ดร., ดร., อ.)",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        max_length=200, verbose_name="ตำแหน่งงาน/หน้าที่รับผิดชอบ"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="วุฒิการศึกษา"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="อีเมล"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="เบอร์โทรศัพท์"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="faculty/",
                        verbose_name="รูปถ่าย",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ลำดับการแสดงผล")),
            ],
            options={
                "verbose_name": "คณาจารย์และบุคลากร",
                "verbose_name_plural": "คณาจารย์และบุคลากร",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="หัวข้อข่าวสาร")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ข่าวประชาสัมพันธ์", "ข่าวประชาสัมพันธ์"),
                            ("กิจกรรมสาขา", "กิจกรรมสาขา"),
                            ("ผลงานนักศึกษา", "ผลงานนักศึกษา"),
                            ("อบรมและสัมมนา", "อบรมและสัมมนา"),
                        ],
                        default="ข่าวประชาสัมพันธ์",
                        max_length=100,
                        verbose_name="หมวดหมู่",
                    ),
                ),
                ("content", models.TextField(verbose_name="เนื้อหาข่าวสาร")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/",
                        verbose_name="รูปภาพประกอบ",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="ข่าวเด่น/ปักหมุด"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่ประกาศ"),
                ),
            ],
            options={
                "verbose_name": "ข่าวสารและกิจกรรม",
                "verbose_name_plural": "ข่าวสารและกิจกรรม",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
