# Generated by Django 6.1 on 2026-08-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="expertise",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="ความเชี่ยวชาญ (เช่น วิทยาการคอมพิวเตอร์)",
            ),
        ),
    ]
